#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Bootstrap the Spaces bucket that holds Part 1 Terraform remote state.
#
# Runs in WSL. doctl supplies the DigitalOcean API token and creates a Spaces
# key when one is not already exported. A local-state Terraform bootstrap using
# the official DigitalOcean provider creates and version-enables the bucket.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BOOTSTRAP="$ROOT/infra/terraform/bootstrap/state"
BUCKET="${HALCYON_TFSTATE_BUCKET:-halcyon-part1-tfstate}"
REGION="${HALCYON_TFSTATE_REGION:-nyc3}"
ENV_OUT="${HALCYON_TFSTATE_ENV_OUT:-$HOME/halcyon-tfstate-backend.env}"
DOCTL_CONTEXT="${DOCTL_CONTEXT:-}"

need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "missing required command: $1" >&2
    exit 1
  }
}

doctl_cmd() {
  if [[ -n "$DOCTL_CONTEXT" ]]; then
    doctl --context "$DOCTL_CONTEXT" "$@"
  else
    doctl "$@"
  fi
}

need doctl
need python3
need terraform

if [[ -z "$DOCTL_CONTEXT" ]] &&
  doctl auth list 2>/dev/null | grep -qx 'admin'; then
  DOCTL_CONTEXT="admin"
fi

echo "== verify WSL doctl authentication =="
echo "doctl context: ${DOCTL_CONTEXT:-default}"
doctl_cmd account get >/dev/null
DIGITALOCEAN_TOKEN="$(doctl_cmd auth token)"
export DIGITALOCEAN_TOKEN

if [[ -z "${SPACES_ACCESS_KEY_ID:-}" || -z "${SPACES_SECRET_ACCESS_KEY:-}" ]]; then
  KEY_NAME="halcyon-tfstate-$(date -u +%Y%m%d%H%M%S)"
  echo "== create Spaces key with doctl (name=$KEY_NAME) =="
  KEY_JSON="$(
    doctl_cmd spaces keys create "$KEY_NAME" \
      --grants 'bucket=;permission=fullaccess' \
      -o json
  )"
  SPACES_ACCESS_KEY_ID="$(
    printf '%s' "$KEY_JSON" |
      python3 -c 'import json,sys; print(json.load(sys.stdin)[0]["access_key"])'
  )"
  SPACES_SECRET_ACCESS_KEY="$(
    printf '%s' "$KEY_JSON" |
      python3 -c 'import json,sys; print(json.load(sys.stdin)[0]["secret_key"])'
  )"
  export SPACES_ACCESS_KEY_ID SPACES_SECRET_ACCESS_KEY
  unset KEY_JSON
fi

if [[ -z "$SPACES_SECRET_ACCESS_KEY" ]]; then
  echo "Spaces secret is empty; delete/recreate the key because secrets are shown once." >&2
  exit 1
fi

umask 077
{
  printf '# Generated by scripts/bootstrap_tf_state.sh — do not commit\n'
  printf '# DigitalOcean credentials only.\n'
  printf 'export DIGITALOCEAN_TOKEN=%q\n' "$DIGITALOCEAN_TOKEN"
  printf 'export SPACES_ACCESS_KEY_ID=%q\n' "$SPACES_ACCESS_KEY_ID"
  printf 'export SPACES_SECRET_ACCESS_KEY=%q\n' "$SPACES_SECRET_ACCESS_KEY"
  printf '# Spaces provider credentials for Terraform bucket resources.\n'
  printf 'export TF_VAR_spaces_access_id="$SPACES_ACCESS_KEY_ID"\n'
  printf 'export TF_VAR_spaces_secret_key="$SPACES_SECRET_ACCESS_KEY"\n'
  printf '# S3-protocol names required by the Terraform remote state backend.\n'
  printf 'export AWS_ACCESS_KEY_ID="$SPACES_ACCESS_KEY_ID"\n'
  printf 'export AWS_SECRET_ACCESS_KEY="$SPACES_SECRET_ACCESS_KEY"\n'
  printf 'export HALCYON_TFSTATE_BUCKET=%q\n' "$BUCKET"
  printf 'export HALCYON_TFSTATE_REGION=%q\n' "$REGION"
} >"$ENV_OUT"

export TF_VAR_bucket_name="$BUCKET"
export TF_VAR_region="$REGION"
export TF_VAR_spaces_access_id="$SPACES_ACCESS_KEY_ID"
export TF_VAR_spaces_secret_key="$SPACES_SECRET_ACCESS_KEY"

echo "== create/version Spaces bucket with DigitalOcean Terraform provider =="
terraform -chdir="$BOOTSTRAP" init -backend=false -input=false
terraform -chdir="$BOOTSTRAP" apply -auto-approve -input=false

echo "wrote $ENV_OUT"
echo "next:"
echo "  source $ENV_OUT"
echo "  bash $ROOT/scripts/production_tf_prep.sh"
echo "notes:"
echo "  - Rotate keys that appear in shell history."
echo "  - Production apply remains a separate, reviewed step."
